module.exports = [
    'AB',   // MOVE
    'ABx',  // LOADK
    'ABC',  // LODABOOL
    'AB',   // LOADNIL
    'AB',   // GETUPVAL
    'ABx',  // GETGLOBAL
    'ABC',  // GETTABLE
    'ABx',  // SETGLOBAL
    'AB',   // SETUPVAL
    'ABC',  // SETTABLE
    'ABC',  // NEWTABLE
    'ABC',  // SELF
    'ABC',  // ADD
    'ABC',  // SUB
    'ABC',  // MUL
    'ABC',  // DIV
    'ABC',  // MOD
    'ABC',  // POW
    'AB',   // UNM
    'AB',   // NOT
    'AB',   // LEN
    'ABC',  // CONCAT
    'sBx',  // JMP
    'ABC',  // EQ
    'ABC',  // LT
    'ABC',  // LE
    'AC',   // TEST
    'ABC',  // TESTSET
    'ABC',  // CALL
    'ABC',  // TAILCALL
    'AB',   // RETURN
    'AsBx', // FORLOOP
    'AsBx', // FORPREP
    'AC',   // TFORLOOP
    'ABC',  // SETLIST
    'A',    // CLOSE
    'ABx',  // CLOSURE
    'AB',   // VARARG

]
